# Generated by Django 4.2.13 on 2024-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
